Create RFC2.md
meower-media-co/RFC pull request #2
Opened 2022-04-07 21:45 UTC by MikeDev101

2022-04-07 22:00 UTC, wgyt requested changes
this PR needs TONS of work and needs to be reviewed by the Moderators team

2022-04-07 22:00 UTC, wgyt commented on RFC2.md
> +4. Main server and user server moderators have remote access to the server to perform standard antivirus software, ddos protection, and other misc. network administrative measures to keep services ru
giving moderators SSH access is a fucking terrible idea, limit SSH access to managers on only the main server

2022-04-07 22:07 UTC, MikeDev101 commented on RFC2.md
> +4. Main server and user server moderators have remote access to the server to perform standard antivirus software, ddos protection, and other misc. network administrative measures to keep services ru
I suppose I wasn't exactly clear but I was going after more of a remote web app to interact with the server. But I do see your point.

2022-04-07 22:30 UTC, wgyt commented on RFC2.md
> +3. All content must be filtered and verified by a minimum amount of user servers running scanners and filters. This will hopefully decrease the chances of malicious and/or obscene content from being
To be clear, I think that filtering on servers other than main server shouldn't be as strict, and that only private servers should have NSFW content

2022-04-07 22:38 UTC, wgyt commented on RFC2.md
> +1. A moderator of the main server will automatically be a moderator of all user servers.
```suggestion
1. A moderator of the main server will become a moderator of all servers that request moderation from the Meower Moderation team```

2022-04-07 23:11 UTC, wgyt approved these changes

2022-04-07 23:29 UTC, wgyt commented
@tnix100 and others might object to this as it uses hub based federation, what do you think about this implementation

2022-04-08 00:07 UTC, merged

2022-04-08 05:45 UTC, tnix100 reviewed
New doc is a lot better, I like the idea of not relying on a main server as much and having most things controlled by a user's "home server". I also didn't like the idea of giving moderators privellage over 3rd party servers.

2022-04-08 16:38 UTC, VelocityDesign commented
Wait so meower is federated now?

2022-04-08 16:53 UTC, MikeDev101 commented
> Wait so meower is federated now?

This RFC sets the foundation for federation within New Meower.